language: cpp

compiler:
  - gcc

sudo: enabled

env:
  global:
    - ROS_DISTRO=indigo

script:
  - source /opt/ros/$ROS_DISTRO/setup.bash
  - cd ~/catkin_ws
  - catkin build
  - source devel/setup.bash
